'use server';

import { revalidatePath } from 'next/cache';
import { FINANCE_PATH, financeError, validId, validateAccount, validateWithdrawal, type FinanceActionState } from '../_lib/finance';
import { financeRequest, readWallet } from '../_queries/finance';

async function mutate(path: string, method: string, payload?: unknown): Promise<FinanceActionState> {
  try {
    const response = await financeRequest(path, { method, ...(payload ? { body: JSON.stringify(payload) } : {}) });
    if (!response.ok) return { success: false, message: response.status === 401 || response.status === 403 ? 'Anda tidak memiliki akses untuk tindakan ini.' : financeError(response.message) };
    revalidatePath(FINANCE_PATH);
    return { success: true, message: 'Perubahan berhasil disimpan.' };
  } catch { return { success: false, message: 'Layanan keuangan tidak tersedia. Coba lagi.' }; }
}

export async function addAccount(_state: FinanceActionState, form: FormData): Promise<FinanceActionState> {
  const account = validateAccount(form);
  if (!account) return { success: false, message: 'Isi kode bank, nomor rekening, dan nama pemilik (maksimal 255 karakter).' };
  return mutate('bank-accounts', 'POST', account);
}

export async function requestWithdrawal(_state: FinanceActionState, form: FormData): Promise<FinanceActionState> {
  const input = validateWithdrawal(form);
  if (!input) return { success: false, message: 'Nominal harus bilangan bulat positif dan pengajuan harus valid.' };
  const balance = await readWallet();
  if (balance.state !== 'ok') return { success: false, message: 'Saldo tidak dapat diverifikasi. Muat ulang dan coba lagi.' };
  if (input.amount > balance.data.available_balance) return { success: false, message: 'Saldo tersedia tidak cukup. Periksa saldo lalu coba lagi.' };
  // A stable key is generated by the form per attempt and survives retries. The
  // backend owns cross-request idempotency and balance/permission checks.
  return mutate('withdrawals', 'POST', input);
}

export async function cancelWithdrawal(_state: FinanceActionState, form: FormData): Promise<FinanceActionState> {
  const id = form.get('id');
  if (!validId(id)) return { success: false, message: 'Pengajuan tidak valid.' };
  return mutate(`withdrawals/${id}`, 'DELETE');
}
