'use client';

import type { Enrollment } from '@/lib/api/types';
import { useActionState } from 'react';
import { saveReport, type ReportActionResponse } from '../_actions/actions';

export function ReportForm({ enrollments, report }: { enrollments: Enrollment[]; report?: { id: string; enrollment_id: string; title: string; evaluation_notes?: string | null; score?: number | null } }) {
  const [state, action, pending] = useActionState(saveReport, { success: false, message: '' } satisfies ReportActionResponse);
  return <form action={action} className="space-y-4 rounded-xl border border-gray-200 bg-white p-5">{report && <input type="hidden" name="id" value={report.id} />}{state.message && <p role="status" className={state.success ? 'rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800' : 'rounded-lg bg-red-50 p-3 text-sm text-red-800'}>{state.message}</p>}{!report && <label className="block text-sm font-medium">Enrollment<select name="enrollment_id" required className="mt-1 min-h-11 w-full rounded-lg border border-gray-300 px-3"><option value="">Pilih enrollment</option>{enrollments.map((item) => <option key={item.id} value={item.id}>{item.student?.full_name || item.student_id} · {item.class?.name || item.class_id}</option>)}</select></label>}{report && <input type="hidden" name="enrollment_id" value={report.enrollment_id} />}<label className="block text-sm font-medium">Judul<input name="title" required defaultValue={report?.title} className="mt-1 min-h-11 w-full rounded-lg border border-gray-300 px-3" /></label><label className="block text-sm font-medium">Catatan<textarea name="evaluation_notes" defaultValue={report?.evaluation_notes || ''} className="mt-1 min-h-24 w-full rounded-lg border border-gray-300 px-3" /></label><label className="block text-sm font-medium">Score<input name="score" type="number" min="0" max="100" step="0.01" defaultValue={report?.score ?? ''} className="mt-1 min-h-11 w-full rounded-lg border border-gray-300 px-3" /></label><button disabled={pending} className="min-h-11 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{pending ? 'Menyimpan...' : report ? 'Simpan perubahan' : 'Buat report'}</button></form>;
}