import type { Metadata } from 'next';
import { EnrollmentForm } from './_components/EnrollmentForm';
import { EnrollmentStatusForm } from './_components/EnrollmentStatusForm';
import { getEnrollmentOptions, getEnrollments } from './_queries/queries';

export const metadata: Metadata = { title: 'Enrollments - Tenant Dashboard', alternates: { canonical: '/dashboard/tenant/enrollments' } };

export default async function EnrollmentsPage({ searchParams }: { searchParams: Promise<{ page?: string; search?: string; status?: string; class_id?: string; student_id?: string }> }) {
  const params = await searchParams;
  const [result, options] = await Promise.all([getEnrollments({ ...params, page: Math.max(1, Number(params.page) || 1) }), getEnrollmentOptions()]);
  return <main className="mx-auto w-full max-w-6xl space-y-6"><header className="border-b border-gray-200 pb-5"><h1 className="text-2xl font-bold text-gray-900">Enrollment management</h1><p className="mt-1 text-sm text-gray-600">Kelola enrollment berdasarkan student dan class dari API.</p></header><div className="grid gap-6 lg:grid-cols-[1fr_2fr]"><EnrollmentForm classes={options.classes.data} students={options.students.data} /><section className="space-y-3"><form method="get" className="grid gap-2 sm:grid-cols-4"><input name="search" defaultValue={params.search} placeholder="Cari" className="min-h-11 rounded-lg border border-gray-300 px-3" /><select name="status" defaultValue={params.status || ''} className="min-h-11 rounded-lg border border-gray-300 px-3"><option value="">Semua status</option><option value="pending">Pending</option><option value="active">Active</option><option value="completed">Completed</option><option value="dropped">Dropped</option></select><select name="student_id" defaultValue={params.student_id || ''} className="min-h-11 rounded-lg border border-gray-300 px-3"><option value="">Semua student</option>{options.students.data.map((student) => <option key={student.id} value={student.id}>{[student.first_name, student.last_name].filter(Boolean).join(' ')}</option>)}</select><button className="min-h-11 rounded-lg bg-gray-900 text-sm font-semibold text-white">Filter</button></form>{result.error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{result.error}</div>}{result.data.length === 0 ? <div className="rounded-xl border border-dashed border-gray-300 bg-white p-8 text-center text-sm text-gray-500">Belum ada enrollment.</div> : result.data.map((enrollment) => <article key={enrollment.id} className="rounded-xl border border-gray-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{enrollment.student ? [enrollment.student.first_name, enrollment.student.last_name].filter(Boolean).join(' ') : enrollment.student_id}</h2><p className="text-sm text-gray-500">{enrollment.class?.name || enrollment.class_id} · {enrollment.billing_cycle || 'billing cycle tidak tersedia'}</p></div><EnrollmentStatusForm id={enrollment.id} status={enrollment.status} /></div></article>)}</section></div></main>;
}
