'use client';

import type { CatalogClass, Student } from '@/lib/api/types';
import Link from 'next/link';
import { useActionState, useId } from 'react';
import { useFormStatus } from 'react-dom';
import { enrollInCatalogClass, type EnrollmentActionResponse } from '../_actions/actions';
import { formatPrice } from '../_lib/formatters';

const initialState: EnrollmentActionResponse = { success: false, message: '' };

function getStudentName(student?: Student): string {
  return student ? [student.first_name, student.last_name].filter(Boolean).join(' ') : 'Selected student';
}

function SubmitButton() { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className="min-h-12 w-full rounded-xl bg-[#17231f] px-5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{pending ? 'Memproses enrollment...' : 'Enroll class ini'}</button>; }

export function EnrollmentPanel({ item, students }: { item: CatalogClass; students: Student[] }) {
  const [state, formAction] = useActionState(enrollInCatalogClass, initialState);
  const idempotencyKey = `enrollment-${useId().replace(/:/g, '')}`;
  if (!item.is_enrollable) return <div className="rounded-2xl border border-[#e6b6a8] bg-[#fff0eb] p-5 text-sm text-[#8d3d29]"><p className="font-bold">Class tidak tersedia untuk enrollment.</p><p className="mt-1">Slot atau status class belum memungkinkan enrollment baru.</p></div>;
  if (!students.length) return <div className="rounded-2xl border border-[#dfe3d7] bg-[#eef1e8] p-5"><h2 className="font-black">Pilih student</h2><p className="mt-2 text-sm text-[#52615b]">Tambahkan student ke akun parent sebelum melanjutkan.</p><Link href="/dashboard/parent/students" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-[#17231f] px-4 text-sm font-bold text-white">Kelola student</Link></div>;
  return <form action={formAction} className="rounded-2xl border border-[#dfe3d7] bg-white p-5 shadow-[0_8px_0_#e9eddf]"><h2 className="text-xl font-black">Enroll class ini</h2><p className="mt-1 text-sm text-[#65726c]">{formatPrice(item.price)} per bulan. Status awal enrollment adalah pending.</p><input type="hidden" name="class_id" value={item.id} /><input type="hidden" name="idempotency_key" value={idempotencyKey} /><div className="mt-5"><label htmlFor="student_id" className="mb-1 block text-sm font-bold">Student</label><select id="student_id" name="student_id" required className="min-h-12 w-full rounded-xl border border-[#c8d0c5] px-3 text-sm"><option value="">Pilih student</option>{students.map((student) => <option key={student.id} value={student.id}>{getStudentName(student)}</option>)}</select></div><div className="mt-4"><label htmlFor="billing_cycle" className="mb-1 block text-sm font-bold">Siklus billing</label><select id="billing_cycle" name="billing_cycle" defaultValue="monthly" className="min-h-12 w-full rounded-xl border border-[#c8d0c5] px-3 text-sm"><option value="monthly">Bulanan</option><option value="quarterly">Per kuartal</option><option value="yearly">Tahunan</option></select></div>{state.message && !state.success && <div role="alert" className="mt-4 rounded-xl bg-[#fff0eb] p-3 text-sm text-[#8d3d29]">{state.message}{state.status === 401 && <Link className="ml-1 font-bold underline" href={`/login?redirectTo=/classes/${item.id}`}>Login</Link>}</div>}{state.success && <div role="status" className="mt-4 rounded-xl bg-[#eef6df] p-4 text-sm text-[#55721f]"><p className="font-bold">{state.message}</p><dl className="mt-3 grid gap-2 text-sm"><div><dt className="inline text-[#65726c]">Status: </dt><dd className="inline font-bold">Pending</dd></div>{state.enrollmentId && <div><dt className="inline text-[#65726c]">ID enrollment: </dt><dd className="inline font-bold">{state.enrollmentId}</dd></div>}<div><dt className="inline text-[#65726c]">Student: </dt><dd className="inline font-bold">{getStudentName(students.find((student) => student.id === state.studentId))}</dd></div><div><dt className="inline text-[#65726c]">Billing: </dt><dd className="inline font-bold">{state.billingCycle || 'monthly'}</dd></div>{state.payment?.gross_amount !== undefined && <div><dt className="inline text-[#65726c]">Total: </dt><dd className="inline font-bold">{formatPrice(state.payment.gross_amount)}</dd></div>}</dl>{state.payment?.checkout_session_url ? <a href={state.payment.checkout_session_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-[#71863a] px-4 font-bold text-white">Lanjut ke pembayaran</a> : <p className="mt-2">Link pembayaran belum tersedia.</p>}</div>}{!state.success && <div className="mt-5"><SubmitButton /></div>}</form>;
}