'use client';

import type { CatalogClass, CatalogSchedule, Student } from '@/lib/api/types';
import { ExternalLink } from 'lucide-react';
import Link from 'next/link';
import { useActionState, useId } from 'react';
import { useFormStatus } from 'react-dom';
import { enrollInCatalogClass, type EnrollmentActionResponse } from '../_actions/actions';
import { formatDayOfWeek, formatPrice, formatTime } from '../_lib/formatters';

const initialState: EnrollmentActionResponse = { success: false, message: '' };

function getStudentName(student?: Student): string { return student ? [student.first_name, student.last_name].filter(Boolean).join(' ') : 'Student terpilih'; }
function getScheduleLabel(schedule: CatalogSchedule): string { return `${formatDayOfWeek(schedule.day_of_week)}, ${formatTime(schedule.start_time)}-${formatTime(schedule.end_time)}`; }
function SubmitButton({ disabled }: { disabled: boolean }) { const { pending } = useFormStatus(); return <button type="submit" disabled={pending || disabled} className="min-h-12 w-full rounded-xl bg-[#17231f] px-5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{pending ? 'Memproses enrollment...' : 'Enroll class ini'}</button>; }

export function EnrollmentPanel({ item, students }: { item: CatalogClass; students: Student[] }) {
  const [state, formAction] = useActionState(enrollInCatalogClass, initialState);
  const idempotencyKey = `enrollment-${useId().replace(/:/g, '')}`;
  const schedules = item.schedules || [];
  const isGroupScheduleRequired = item.type === 'group';
  const availableSchedules = schedules.filter((schedule) => schedule.is_available && schedule.available_slots > 0);
  const selectedSchedule = schedules.find((schedule) => schedule.id === state.scheduleId);
  const selectedStudent = students.find((student) => student.id === state.studentId);
  const paymentUrl = state.payment?.checkout_session_url?.trim();
  if (!item.is_enrollable) return <div className="rounded-2xl border border-[#e6b6a8] bg-[#fff0eb] p-5 text-sm text-[#8d3d29]"><p className="font-bold">Class tidak tersedia untuk enrollment.</p><p className="mt-1">Slot atau status class belum memungkinkan enrollment baru.</p></div>;
  if (isGroupScheduleRequired && !availableSchedules.length) return <div role="alert" className="rounded-2xl border border-[#e6b6a8] bg-[#fff0eb] p-5 text-sm text-[#8d3d29]"><p className="font-bold">Belum ada schedule group yang tersedia.</p><p className="mt-1">Semua schedule penuh atau tidak aktif. Enrollment belum dapat dilanjutkan.</p></div>;
  if (!students.length) return <div className="rounded-2xl border border-[#dfe3d7] bg-[#eef1e8] p-5"><h2 className="font-black">Pilih student</h2><p className="mt-2 text-sm text-[#52615b]">Tambahkan student ke akun parent sebelum melanjutkan.</p><Link href="/dashboard/parent/students" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-[#17231f] px-4 text-sm font-bold text-white">Kelola student</Link></div>;
  return <form action={formAction} className="rounded-2xl border border-[#dfe3d7] bg-white p-5 shadow-[0_8px_0_#e9eddf]"><h2 className="text-xl font-black">Enroll class ini</h2><p className="mt-1 text-sm text-[#65726c]">{formatPrice(item.price)} per bulan. Status awal enrollment adalah pending.</p><input type="hidden" name="class_id" value={item.id} /><input type="hidden" name="class_type" value={item.type} /><input type="hidden" name="idempotency_key" value={idempotencyKey} />{isGroupScheduleRequired && <fieldset disabled={state.success} className="mt-5"><legend className="mb-2 text-sm font-bold">Pilih schedule</legend><div className="grid gap-2">{schedules.map((schedule) => { const isFull = !schedule.is_available || schedule.available_slots <= 0; return <label key={schedule.id} className={`flex min-h-12 cursor-pointer gap-3 rounded-xl border p-3 text-sm ${isFull ? 'cursor-not-allowed border-[#e6e8e2] bg-[#f5f6f2] text-[#8b948e]' : 'border-[#c8d0c5] has-[:checked]:border-[#71863a] has-[:checked]:bg-[#eef6df]'}`}><input type="radio" name="schedule_id" value={schedule.id} disabled={isFull} required className="mt-1 h-4 w-4 accent-[#71863a]" defaultChecked={schedule.id === state.scheduleId} /><span className="min-w-0"><span className="block font-bold">{getScheduleLabel(schedule)}</span><span className="block break-words text-[#65726c]">{isFull ? 'Penuh atau tidak tersedia' : `${schedule.available_slots} slot tersedia`}{schedule.location ? ` · ${schedule.location}` : ''}</span></span></label>; })}</div></fieldset>}
    <div className="mt-5"><label htmlFor="student_id" className="mb-1 block text-sm font-bold">Student</label><select id="student_id" name="student_id" required disabled={state.success} defaultValue={state.studentId || ''} className="min-h-12 w-full rounded-xl border border-[#c8d0c5] px-3 text-sm"><option value="">Pilih student</option>{students.map((student) => <option key={student.id} value={student.id}>{getStudentName(student)}</option>)}</select></div><div className="mt-4"><label htmlFor="billing_cycle" className="mb-1 block text-sm font-bold">Siklus billing</label><select id="billing_cycle" name="billing_cycle" required disabled={state.success} defaultValue={state.billingCycle || 'monthly'} className="min-h-12 w-full rounded-xl border border-[#c8d0c5] px-3 text-sm"><option value="monthly">Bulanan</option><option value="quarterly">Per kuartal</option><option value="yearly">Tahunan</option></select></div>{state.message && !state.success && <div role="alert" className="mt-4 rounded-xl bg-[#fff0eb] p-3 text-sm text-[#8d3d29]">{state.message}{state.status === 401 && <Link className="ml-1 font-bold underline" href={`/login?redirectTo=/classes/${item.id}`}>Login</Link>}</div>}{state.success && <div role="status" className="mt-4 rounded-xl bg-[#eef6df] p-4 text-sm text-[#55721f]"><p className="font-bold">{state.message}</p><dl className="mt-3 grid gap-2 text-sm"><div><dt className="inline text-[#65726c]">Student: </dt><dd className="inline font-bold">{selectedStudent ? getStudentName(selectedStudent) : 'Student terpilih'}</dd></div><div><dt className="inline text-[#65726c]">Class: </dt><dd className="inline font-bold">{item.name}</dd></div>{selectedSchedule && <div><dt className="inline text-[#65726c]">Schedule: </dt><dd className="inline font-bold">{getScheduleLabel(selectedSchedule)}</dd></div>}<div><dt className="inline text-[#65726c]">Siklus billing: </dt><dd className="inline font-bold">{state.billingCycle || 'Bulanan'}</dd></div><div><dt className="inline text-[#65726c]">Nominal: </dt><dd className="inline font-bold">{state.payment ? formatPrice(state.payment.gross_amount) : formatPrice(item.price)}</dd></div><div><dt className="inline text-[#65726c]">Status enrollment: </dt><dd className="inline font-bold">Pending</dd></div></dl>{paymentUrl && <a href={paymentUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#17231f] px-4 text-sm font-bold text-white">Lanjut ke payment <ExternalLink size={16} aria-hidden="true" /></a>}</div>}<div className="mt-5"><SubmitButton disabled={state.success} /></div></form>;
}
