import { getParentStudents } from '@/app/(dashboard)/dashboard/parent/_queries/queries';
import { getAuthCookieName } from '@/lib/api/client';
import { decodeTokenClaims, getDashboardRole, getTokenStatus } from '@/lib/auth/token';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { EnrollmentPanel } from '../_components/EnrollmentPanel';
import { formatDistance, formatPrice } from '../_lib/formatters';
import { getCatalogClass } from '../_queries/queries';

const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; const result = await getCatalogClass(id); if (!result.data) return { title: 'Class tidak ditemukan - KelolaKelas', robots: { index: false, follow: false } }; const title = `${result.data.name} - ${result.data.tenant_name}`; const description = typeof result.data.description === 'string' ? result.data.description : `Pelajari detail ${result.data.name} dari ${result.data.tenant_name}.`; return { title, description, alternates: { canonical: `${appUrl}/classes/${id}` }, openGraph: { title, description, url: `${appUrl}/classes/${id}`, type: 'website' }, robots: { index: true, follow: true } }; }

export default async function ClassDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const result = await getCatalogClass(id); if (!result.data && result.status === 404) notFound(); if (!result.data) return <main className="flex min-h-screen items-center justify-center bg-[#f8f7f3] p-5"><div role="alert" className="rounded-2xl border border-[#e6b6a8] bg-white p-7 text-center"><h1 className="text-xl font-black">Detail class gagal dimuat</h1><p className="mt-2 text-sm text-[#65726c]">{result.error || 'Coba lagi nanti.'}</p><Link href="/classes" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#17231f] px-4 text-sm font-bold text-white">Kembali ke katalog</Link></div></main>;
  const token = (await cookies()).get(getAuthCookieName())?.value; let role = 'guest'; try { if (token && getTokenStatus(token) === 'valid') role = getDashboardRole(decodeTokenClaims(token)); } catch { role = 'guest'; } const students = role === 'parent' ? (await getParentStudents()).data : []; const distance = formatDistance(result.data.distance_km);
  return <main className="min-h-screen bg-[#f8f7f3] text-[#17231f]"><header className="mx-auto max-w-5xl px-5 py-5"><Link href="/classes" className="text-sm font-bold text-[#55721f]">← Kembali ke katalog</Link></header><section className="mx-auto grid max-w-5xl gap-8 px-5 pb-16 pt-8 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#71863a]">{result.data.category_name}</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl">{result.data.name}</h1><p className="mt-4 text-lg font-bold text-[#52615b]">{result.data.tenant_name}</p><p className="mt-1 text-sm text-[#65726c]">{result.data.tenant_address || 'Alamat tenant belum tersedia'}</p><div className="mt-8 rounded-2xl border border-[#dfe3d7] bg-white p-6"><h2 className="text-xl font-black">Tentang class</h2><p className="mt-3 whitespace-pre-wrap text-[#52615b]">{typeof result.data.description === 'string' ? result.data.description : 'Deskripsi class belum tersedia.'}</p><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[#65726c]">Tipe</dt><dd className="font-bold">{result.data.type}</dd></div><div><dt className="text-[#65726c]">Harga</dt><dd className="font-bold">{formatPrice(result.data.price)} / bulan</dd></div><div><dt className="text-[#65726c]">Kapasitas</dt><dd className="font-bold">{result.data.capacity ?? 'Tidak tersedia'}</dd></div><div><dt className="text-[#65726c]">Slot tersedia</dt><dd className="font-bold">{result.data.available_slots ?? 'Tidak tersedia'}</dd></div>{distance && <div><dt className="text-[#65726c]">Jarak dari pencarian</dt><dd className="font-bold">{distance}</dd></div>}</dl></div></div><aside>{role === 'guest' ? <div className="rounded-2xl border border-[#dfe3d7] bg-white p-5 shadow-[0_8px_0_#e9eddf]"><h2 className="text-xl font-black">Tertarik dengan class ini?</h2><p className="mt-2 text-sm text-[#65726c]">Login sebagai parent untuk memilih student dan siklus billing.</p><Link href={`/login?redirectTo=/classes/${id}`} className="mt-5 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#17231f] px-5 text-sm font-bold text-white">Login untuk enroll</Link></div> : role === 'parent' ? <EnrollmentPanel item={result.data} students={students} /> : <div className="rounded-2xl border border-[#dfe3d7] bg-[#eef1e8] p-5 text-sm text-[#52615b]">Enrollment class publik hanya tersedia untuk akun parent.</div>}</aside></section></main>;
}