import type { Metadata } from 'next';
import Link from 'next/link';
import { getEnrollments } from '../enrollments/_queries/queries';
import { BillingForm } from './_components/BillingForm';
import { getTransactions } from './_queries/queries';

export const metadata: Metadata = { title: 'Billing - Tenant Dashboard', alternates: { canonical: '/dashboard/tenant/billing' } };

export default async function BillingPage({ searchParams }: { searchParams: Promise<{ page?: string; search?: string; status?: string; date_from?: string; date_to?: string }> }) { const params = await searchParams; const [transactions, enrollments] = await Promise.all([getTransactions({ ...params, page: Math.max(1, Number(params.page) || 1) }), getEnrollments({ page: 1 })]); return <main className="mx-auto w-full max-w-6xl space-y-6"><header className="border-b border-gray-200 pb-5"><h1 className="text-2xl font-bold">Billing</h1><p className="mt-1 text-sm text-gray-600">Checkout dan riwayat transaksi tenant.</p></header><div className="grid gap-6 lg:grid-cols-[1fr_2fr]"><BillingForm enrollments={enrollments.data} /><section className="space-y-3"><form method="get" className="grid gap-2 sm:grid-cols-4"><input name="search" defaultValue={params.search} placeholder="Cari transaksi" className="min-h-11 rounded-lg border border-gray-300 px-3" /><select name="status" defaultValue={params.status || ''} className="min-h-11 rounded-lg border border-gray-300 px-3"><option value="">Semua status</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="expired">Expired</option></select><input name="date_from" type="date" defaultValue={params.date_from} className="min-h-11 rounded-lg border border-gray-300 px-3" /><button className="min-h-11 rounded-lg bg-gray-900 text-sm font-semibold text-white">Filter</button></form>{transactions.error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{transactions.error}</div>}{transactions.data.length === 0 ? <div className="rounded-xl border border-dashed border-gray-300 bg-white p-8 text-center text-sm text-gray-500">Belum ada transaksi.</div> : transactions.data.map((transaction) => <article key={transaction.id || transaction.transaction_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 bg-white p-4"><div><h2 className="font-semibold">{transaction.currency || 'IDR'} {transaction.gross_amount.toLocaleString('id-ID')}</h2><p className="text-sm text-gray-500">{transaction.status} · {transaction.paid_at?.slice(0, 10) || 'Belum dibayar'}</p></div><Link href={`/dashboard/tenant/billing/${transaction.id || transaction.transaction_id}`} className="text-sm font-semibold text-blue-700">Detail</Link>{transaction.checkout_session_url && transaction.status !== 'paid' && <a href={transaction.checkout_session_url} className="text-sm font-semibold text-blue-700">Buka checkout</a>}</article>)}</section></div></main>; }
